### ISSUE TITLE
English Translation

### ISSUE THREAD

**Issue by EmpireWorld** [CatLib/CatLib#1]
Hi, It would be good if you provide English translation for this repository.

Thanks.

**Comment by yb199478** [comment]
We have joined the plan for English translation，Please look forward to it.

**Comment by EmpireWorld** [comment]
I hope I could, but I don't know the current language of the repository, Chinese or Korea, anyway I don't know these languages sorry, :)

**Comment by yb199478** [comment]
Maybe you can correct some of the semantics after we finish the translation

**Comment by yb199478** [comment]
Our translation will begin with the code portion of CatLib.Core ， Document section second

**Comment by ymh199478** [comment]
English translation has been completed, CatLib is now in English.
