### ISSUE TITLE
关于timermanager 的

### ISSUE THREAD

**Issue by willcong** [CatLib/CatLib#25]
在update 的foreach 里面循环移除元素不会抛异常么？

**Comment by yb199478** [comment]
不会，这是我们自己实现的数据结构，所以不会有问题，对foreach是友好的。

**Comment by yb199478** [comment]
在循环内修改抛异常的根本原因是由于删除元素或者增加元素导致内部数组偏移发生变化，最终导致迭代器不能反馈预期的值。这时候.net的开发人员就加入了安全检查。如果检查到了变化那么主动抛出一个异常。

而catlib使用的sortset是我们自己实现的数据结构，底层实现是链表。所以可以友好的支持迭代内修改（当然我们也做了明确其迭代行为的处理）。

**Comment by willcong** [comment]
soga，没整体看，懂了，谢谢详细解答哈。
