### ISSUE TITLE
[Question]关于OnStartCompleted的执行顺序

### ISSUE THREAD

**Issue by Tino23X** [CatLib/CatLib#38]
CatLib For Unity version 1.4
CatLib Core version 1.4
Unity 2018.3

直接运行Demo时，OnStartCompleted执行是在application.init之后就执行的。
把一个测试服务加入到Demo\Runtime\Config\Providers文件后，在application.init开始执行之后会跳过两帧才执行OnStartCompleted。
我的测试服务里无实际功能代码，也无协同。
这个OnStartCompleted执行顺序是否可控?

**Comment by yb199478** [comment]
你是否添加了2个服务提供者？

**Comment by Tino23X** [comment]
我的修改过的几个文件是这样的
IServiceTest.cs
`
public interface IserviceTest
{
    void Print();
}`


ProviderServiceTest.cs
`public class ProviderServiceTest :IServiceProvider
{
    public void Init()
    {
        App.Make<IserviceTest>().Print();
        
    }

    public void Register()
    {
        App.Singleton<IserviceTest, ServiceTest>();
    }
}`


ServiceTest.cs
`public class ServiceTest : IserviceTest
{
    public void Print()
    {
        Debug.Log("test...");
    }
}`


Demo\Runtime\Main.cs 就增加了Update函数
`void Update()
{
  Debug.Log("Update.....");
}`

Demo\Runtime\Config\Providers.cs
`    public static class Providers
    {
        /// <summary>
        /// 项目注册的服务提供者
        /// </summary>
        public static IServiceProvider[] ServiceProviders
        {
            get
            {
                return new IServiceProvider[]
                {
                    new ProviderServiceTest(), 
                };
            }
        }
    }`

其他的文件都没修改过

**Comment by yb199478** [comment]
我们审查了代码，这个问题可能是由于：https://github.com/CatLib/CatLib/blob/2a0d850af6074aaae2bcc77c19fc073b07ac3b44/CatLib/Runtime/UnityApplication.cs#L73

导致的，由于`ServiceProvider`默认实现了迭代器初始化，而内部代码默认情况使用了`yield break;`，所以Unity的协同程序会等待一帧。那么可能导致2个服务等待2帧的问题。

**Comment by yb199478** [comment]
不知道你有没有兴趣去验证一下这个功能？或者发起一个`pull request`来修复这个问题?

**Comment by Tino23X** [comment]
嗯，我先去查验一下

**Comment by yb199478** [comment]
从目前看来确实是Unity的机制导致，等待帧执行。

**Comment by yb199478** [comment]
不建议直接去修改引导库的代码，已经出现问题的项目可以通过继承`UnityApplication.cs`并重写的的方式来修复这个问题。

```csharp
/// <summary>
/// 初始化服务提供者
/// </summary>
public override void Init()
{
    if (Behaviour)
    {
        Behaviour.StartCoroutine(InitWithUnityCoroutine());
        return;
    }
    base.Init();
}
```
```csharp
/// <summary>
/// 使用Unity协同程序初始化服务提供者.
/// </summary>
/// <returns>协同程序</returns>
/// <see cref="https://github.com/CatLib/CatLib/issues/38">
protected IEnumerator InitWithUnityCoroutine()
{
    var coroutine = CoroutineInit();
    while (coroutine.MoveNext())
    {
        if (!(coroutine.Current is IEnumerator frameworkCoroutine))
        {
            continue;
        }

        while (frameworkCoroutine.MoveNext())
        {
            if (frameworkCoroutine.Current is IEnumerator logicCoroutine)
            {
                yield return logicCoroutine;
            }
        }
    }
}
```

**Comment by yb199478** [comment]
@Tino23X  如果可以的话你可以发起一个`pull request`来立即修复这个问题或者等待我们的修复周期.

**Comment by Tino23X** [comment]
嗯嗯，好的，只是我现在还没有信心，还需要继续学习-_-||
