### ISSUE TITLE
能否提供更明确的小游戏示例？

### ISSUE THREAD

**Issue by zgdawn** [CatLib/CatLib#4]
对于很多游戏客户端程序员来讲，所谓的依赖注入，路由这种东西，可以说完全没有接触过，
特别是有些C++转过来的程序员（比如我啦），
对于依赖注入这种东西，完全体会不到好处在哪里(没办法，C++很多东西都要自己手动轮一下）
所以对于各模块，不知作者是否有计划逐步添加示例？

**Comment by yb199478** [comment]
CatLib已经提供了完善的文档支持暂时不会考虑添加更多运行时示例。您可以参考[1.3版本的文档](https://github.com/CatLib/CatLib.io/tree/1.3)，1.3版本的文档会更加的清晰。

您也可以加群，群里的童学或许会给您提供更多的帮助。

**Comment by zgdawn** [comment]
谢谢回复
个人认为q群不是一个讨论问题的好地方，可以引导大家直接来这里讨论啊
便于检索，干扰比较少。
我有空会动手研究一下

**Comment by yb199478** [comment]
嗯，我们是鼓励在issues中讨论，但是国内环境影响，q群还是很多人喜欢。
